name: CI

on:
  push:
    branches:
    - master
    - develop
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: composer install
      run: composer install
    - name: phpcbf
      run: php ./vendor/bin/phpcbf
    - name: phpunit
      run: php ./vendor/bin/phpunit
    - name: phpinsights
      run: php ./vendor/bin/phpinsights -n
